//FELIZ, SORRINDO, TRISTE, PREOCUPADO, CHORANDO, ENGRAÇADO, COM FOME, COM SONO, COM RAIVA, IRRITADO, PENSATIVO, ASSUSTADO,
//SEM ENTENDER

List<Map<String, dynamic>> conceitosList = [
  {
    'conceito': 'FELIZ',
    'fotos': ['jogandoFutebol.jpg', 'feliz.jpg', 'feliz2.jpg'],
    'emojis-corretos': [
      "caraSorridente1.png",
      "caraSorridente2.png",
      "caraSorridente3.png",
      "caraChorandoAlegria.png",
      "caraDandoRisada.png",
      "caraEngracada2.png",
      "caraOlhosCoracoes1.png",
      "caraOlhosCoracoes2.png",
      "caraOlhosEstrela.png",
      "caraPiscandoOlhos1.png",
      "caraMostrandoLingua1.png",
      "caraMostrandoLingua2.png",
      "caraMostrandoLingua3.png",
      "caraAnjo.png",
      "caraOculosSol.png",
      "caraTranquila.png",
      "caraInteligente.png",
      "caraSorrindoComSuor.png",
    ],
  },
  {
    'conceito': 'ASSUSTADO',
    'fotos': ['assustado.jpg', 'assustado2.jpg', 'assustado3.jpg'],
    'emojis-corretos': [
      "caraAssustados1.png",
      "caraAssustados2.png",
      "caraAssutada.png",
      "caraPreocupada.png",
      "caraPreocupadaSuor1.png",
      "caraPreocupadaSuor2.png",
    ],
  },
  {
    'conceito': 'CHORANDO',
    'fotos': ['chorando.jpg', 'chorando2.jpg', 'chorando3.jpg'],
    'emojis-corretos': [
      "caraChorandoMuito.png",
      "caraMuitoTriste1.png",
      "caraMuitoTriste2.png",
      "caraPedindoAlgumaCoisa.png",
      "caraCansada1.png",
      "caraCansada2.png",
      "caraNaoEntendo.png",
    ],
  },
  {
    'conceito': 'CONFUSO',
    'fotos': ['confuso.jpg', 'confuso2.png', 'confuso3.jpg'],
    'emojis-corretos': [
      "caraDePensativo.png",
      "caraDesconfiada1.png",
      "caraDesconfiada2.png",
    ],
  },
  {
    'conceito': 'ENGRAÇADO',
    'fotos': ['engracado.jpg', 'engracado2.jpeg', 'assistirFilme.jpg'],
    'emojis-corretos': [
      "caraSorridente1.png",
      "caraSorridente2.png",
      "caraSorridente3.png",
      "caraChorandoAlegria.png",
      "caraDandoRisada.png",
      "caraEngracada2.png",
      "caraOlhosCoracoes1.png",
      "caraOlhosCoracoes2.png",
      "caraOlhosEstrela.png",
      "caraSorrindoComSuor.png",
    ],
  },
  {
    'conceito': 'FOME',
    'fotos': ['fome.jpg', 'fome2.jpg', 'fome3.jpg'],
    'emojis-corretos': [
      "caraFome.png",
    ],
  },
  {
    'conceito': 'IRRITADO',
    'fotos': ['irritado.jpeg', 'irritado2.jpg', 'malEducado.jpg'],
    'emojis-corretos': [
      "caraIrritado.png",
      "caraMuitaRaiva.png",
      "caraVirandoOsOlhos.png",
    ],
  },
  {
    'conceito': 'PENSATIVO',
    'fotos': ['pensativo.jpg', 'pensativo2.jpg', 'pensativo3.jpg'],
    'emojis-corretos': [
      "caraDePensativo.png",
    ],
  },
  {
    'conceito': 'PREOCUPADO',
    'fotos': ['preocupado.png', 'preocupado2.jpg', 'preocupado3.jpg'],
    'emojis-corretos': [
      "caraPreocupada.png",
      "caraPreocupadaSuor1.png",
      "caraPreocupadaSuor2.png",
    ],
  },
  {
    'conceito': 'RAIVA',
    'fotos': ['raiva.jpg', 'raiva2.jpg', 'raiva3.jpg'],
    'emojis-corretos': [
      "caraRaiva.png",
      "caraIrritado.png",
      "caraMuitaRaiva.png",
    ],
  },
  {
    'conceito': 'SONO',
    'fotos': ['sono.jpg', 'sono2.jpg', 'sono3.jpg'],
    'emojis-corretos': [
      "caraComSono1.png",
      "caraComSono2.png",
      "caraBocejando.png",
    ],
  },
  {
    'conceito': 'SORRINDO',
    'fotos': ['sorrindo.jpg', 'sorrindo2.jpg', 'sorrindo3.jpg'],
    'emojis-corretos': [
      "caraDandoRisada.png",
      "caraSorridente1.png",
      "caraSorridente2.png",
      "caraSorridente3.png",
      "caraSorrindoComSuor.png",
    ],
  },
  {
    'conceito': 'TRISTE',
    'fotos': ['triste.jpg', 'triste2.jpg', 'triste3.jpg'],
    'emojis-corretos': [
      "caraMuitoTriste1.png",
      "caraMuitoTriste2.png",
      "caraTriste1.png",
      "caraTriste2.png",
      "caraPreocupada.png",
      "caraPreocupadaSuor1.png",
      "caraPreocupadaSuor2.png",
      "caraCansada1.png",
      "caraCansada2.png",
    ],
  },
];
