Map<String, String> sugestaoPersonalidade = {
  "HOMEM": 'homem.jpg',
  "MULHER": 'mulher.jpg',
  "UMA PESSOA JOVEM": 'jovem.jpg',
  "UMA PESSOA ADULTA": 'adulto.jpg',
  "UMA PESSOA TRANQUILA": 'tranquila.jpg',
  "UMA PESSOA CALMA": 'calma.jpg',
  "UMA PESSOA FELIZ": 'feliz.jpg',
  "UMA PESSOA AGITADA": 'agitada.jpg',
};
Map<String, String> sugestaoCorPele = {
  "BRANCA": 'branca.jpg',
  "PARDA": 'parda.jpg',
  "PRETA": 'preta.jpg',
  "AMARELA": 'amarela.jpg',
  "NEGRA": 'negra.jpg',
  "MORENA": 'morena.jpg',
};
Map<String, String> sugestaoCorOlho = {
  "PRETO": 'publico.png',
  "AZUL": 'publico.png',
  "VERDE": 'publico.png',
  "CASTANHO": 'publico.png',
};
Map<String, String> sugestaoComidaPreferida = {
  "ARROZ E FEIJÃO": 'publico.png',
  "MACARRÃO": 'publico.png',
  "BIFE": 'publico.png',
  "FRANGO": 'publico.png',
  "SANDUÍCHE": 'publico.png',
  "CHURRASCO": 'publico.png',
  "PEIXE": 'publico.png',
  "PIZZA": 'publico.png',
  "COXINHA": 'publico.png',
  "SOPA": 'publico.png',
  "SALADA": 'publico.png',
  "OVO": 'publico.png',
  "BOLO": 'publico.png',
  "BATATA FRITA": 'publico.png',
  "CUSCUZ": 'publico.png',
  "TAPIOCA": 'publico.png',
  "PÃO": 'publico.png',
};

Map<String, String> sugestaoGostoDe = {
  "VIAJAR": 'publico.png',
  "LER": 'publico.png',
  "CINEMA": 'publico.png',
  "SHOPPING": 'publico.png',
  "ANDAR DE BICICLETA": 'publico.png',
  "SAIR COM AMIGOS": 'publico.png',
  "TEATRO": 'publico.png',
  "DANÇAR": 'publico.png',
  "NADAR": 'publico.png',
  "PRAIA": 'publico.png',
  "PISCINA": 'publico.png',
  "PARQUE": 'publico.png',
  "CAMINHAR": 'publico.png',
  "CORRER": 'publico.png',
  "ACADEMIA": 'publico.png',
  "JOGAR FUTEBOL": 'publico.png',
  "CAPOEIRA": 'publico.png',
  "COZINHAR": 'publico.png',
  "FAZER ARTESANATO": 'publico.png',
  "CUIDAR DE PLANTAS": 'publico.png',
  "AVIÃO": 'publico.png',
  "PLANETAS": 'publico.png',
  "MONTANHA": 'publico.png',
  "CACHOEIRA": 'publico.png',
  "VER TELEVISÃO": 'publico.png',
  "JOGAR VIDEO GAME": 'publico.png',
  "PESCAR": 'publico.png',
};

Map<String, String> sugestaoNaoGostoDe = {
  "ACORDAR CEDO": 'publico.png',
  "PESSOAS MAL EDUCADAS": 'publico.png',
  "SOM ALTO": 'publico.png',
  "DORMIR TARDE": 'publico.png',
  "CHUVA": 'publico.png',
  "SOL FORTE": 'publico.png',
  "FAZER ATIVIDADE FÍSICA": 'publico.png',
  "COMER VERDURAS": 'publico.png',
  "FOFOCA": 'publico.png',
  "TRÂNSITO": 'publico.png',
  "BUZINA": 'publico.png',
  "COMIDA FRIA": 'publico.png',
  "COMIDA QUENTE": 'publico.png',
  "FICAR SOZINHO": 'publico.png',
  "FICAR SOZINHA": 'publico.png',
  "ELEVADOR": 'publico.png',
  "ESCADA ROLANTE": 'publico.png',
};

Map<String, String> sugestaoCorPreferida = {
  "AZUL CLARO": 'publico.png',
  "AZUL ESCURO": 'publico.png',
  "AMARELO": 'publico.png',
  "ROSA CLARO": 'publico.png',
  "ROSA PINK": 'publico.png',
  "VERDE": 'publico.png',
  "PRETO": 'publico.png',
  "BRANCO": 'publico.png',
  "CINZA": 'publico.png',
  "BEGE": 'publico.png',
  "LILÁS": 'publico.png',
  "LARANJA": 'publico.png',
  "VERMELHO": 'publico.png',
};

Map<String, String> sugestaoSigno = {
  "ÁRIES": 'publico.png',
  "LIBRA": 'publico.png',
  "VIRGEM": 'publico.png',
  "LEÃO": 'publico.png',
  "SAGITÁRIO": 'publico.png',
  "PEIXES": 'publico.png',
  "ESCORPIÃO": 'publico.png',
  "AQUÁRIO": 'publico.png',
  "TOURO": 'publico.png',
  "CÂNCER": 'publico.png',
  "GÊMEOS": 'publico.png',
  "CAPRICÓRNIO": 'publico.png',
};

Map<String, String> sugestaoEscolaridade = {
  "ENSINO FUNDAMETAL": 'publico.png',
  "ENSINO MÉDIO": 'publico.png',
  "FACULDADE": 'publico.png',
  "EDUCAÇÃO AO LONGO DA VIDA": 'publico.png',
};

Map<String, String> sugestaoAtividades = {
  "ARTESANATO": 'publico.png',
  "PINTURA": 'publico.png',
  "DANÇA": 'publico.png',
  "ARTES": 'publico.png',
  "MÚSICA": 'publico.png',
  "ESPORTE": 'publico.png',
  "JARDINAGEM": 'publico.png',
  "HORTA": 'publico.png',
  "CULINÁRIA": 'publico.png',
  "JOGOS": 'publico.png',
  "ALFABETIZAÇÃO": 'publico.png',
};

Map<String, String> sugestaoRelacionamento = {
  "SOLTEIRO": 'publico.png',
  "NAMORANDO (RELACIONAMENTO SÉRIO)": 'publico.png',
  "CASADO": 'publico.png',
  "NOIVO": 'publico.png',
  "VIÚVO": 'publico.png',
};

Map<String, String> sugestaoHobbies = {
  "ARTESANATO": 'publico.png',
  "DANÇAR": 'publico.png',
  "OUVIR MÚSICA": 'publico.png',
  "FAZER TEATRO": 'publico.png',
  "FAZER DOBRADURAS (ORIGAMI)": 'publico.png',
  "TOCAR INSTRUMENTO MUSICAL": 'publico.png',
  "JARDINAGEM": 'publico.png',
  "CULINÁRIA": 'publico.png',
  "JOGOS": 'publico.png',
  "LEITURA": 'publico.png',
  "ASSISTIR FILME": 'publico.png',
  "FOTOGRAFIA": 'publico.png',
  "ENCONTRAR AMIGOS": 'publico.png',
  "FAZER PALAVRA CRUZADA": 'publico.png',
  "PASSEAR COM CACHORRO": 'publico.png',
  "VIAJAR": 'publico.png',
  "FAZER QUEBRA CABEÇA": 'publico.png',
  "PESCARIA": 'publico.png',
  "ACAMPAR": 'publico.png',
  "FAZER TRILHA": 'publico.png',
  "COLECIONAR COISAS": 'publico.png',
};

Map<String, String> sugestaoPrivacidade = {
  "PÚBLICO": 'publico.png',
  "PRIVADO": 'publico.png',
};
