Map<String, String> sugestaoPersonalidade = {
  "HOMEM": 'homem.jpg',
  "MULHER": 'mulher.jpg',
  "UMA PESSOA JOVEM": 'jovem.jpg',
  "UMA PESSOA ADULTA": 'adulto.jpg',
  "UMA PESSOA TRANQUILA": 'tranquila.jpg',
  "UMA PESSOA CALMA": 'calma.jpg',
  "UMA PESSOA FELIZ": 'feliz.jpg',
  "UMA PESSOA AGITADA": 'agitada.jpg',
};
Map<String, String> sugestaoCorPele = {
  "BRANCA": 'branca.jpg',
  "PARDA": 'parda.jpg',
  "PRETA": 'preta.jpg',
  "AMARELA": 'amarela.jpg',
  "NEGRA": 'negra.jpg',
  "MORENA": 'morena.jpg',
};
Map<String, String> sugestaoCorOlho = {
  "PRETO": 'olhoPreto.jpg',
  "AZUL": 'olhoAzul.jpg',
  "VERDE": 'olhoVerde.jpg',
  "CASTANHO": 'olhoCastanho.jpg',
};
Map<String, String> sugestaoComidaPreferida = {
  "ARROZ E FEIJÃO": 'arrozEfeijao.jpg',
  "MACARRÃO": 'macarrao.jpg',
  "BIFE": 'bife.jpg',
  "FRANGO": 'frango.jpg',
  "SANDUÍCHE": 'sanduiche.jpg',
  "CHURRASCO": 'churrasco.jpg',
  "PEIXE": 'peixe.jpg',
  "PIZZA": 'pizza.jpg',
  "COXINHA": 'coxinha.jpg',
  "SOPA": 'sopa.jpg',
  "SALADA": 'salada.jpg',
  "OVO": 'ovo.jpg',
  "BOLO": 'bolo.jpg',
  "BATATA FRITA": 'batataFrita.jpg',
  "CUSCUZ": 'cuscuz.jpg',
  "TAPIOCA": 'tapioca.jpg',
  "PÃO": 'pao.jpg',
};

Map<String, String> sugestaoGostoDe = {
  "VIAJAR": 'viajar.jpg',
  "LER": 'ler.jpg',
  "CINEMA": 'cinema.jpg',
  "SHOPPING": 'shopping.jpg',
  "ANDAR DE BICICLETA": 'bicicleta.jpg',
  "SAIR COM AMIGOS": 'sairComAmigos.jpg',
  "TEATRO": 'teatro.jpg',
  "DANÇAR": 'dancar.jpg',
  "NADAR": 'nadar.jpg',
  "PRAIA": 'praia.jpg',
  "PISCINA": 'piscina.jpg',
  "PARQUE": 'parque.jpg',
  "CAMINHAR": 'caminhar.jpg',
  "CORRER": 'correr.jpg',
  "ACADEMIA": 'academia.jpg',
  "JOGAR FUTEBOL": 'futebol.jpg',
  "CAPOEIRA": 'capoeira.jpg',
  "COZINHAR": 'cozinhar.jpg',
  "FAZER ARTESANATO": 'artesanato.jpg',
  "CUIDAR DE PLANTAS": 'cuidarDePlantas.jpg',
  "AVIÃO": 'aviao.jpg',
  "PLANETAS": 'planetas.jpg',
  "MONTANHA": 'montanhas.jpg',
  "CACHOEIRA": 'cachoeira.jpg',
  "VER TELEVISÃO": 'assistirTV.jpg',
  "JOGAR VIDEO GAME": 'jogarVideoGame.jpg',
  "PESCAR": 'pescar.jpg',
};

Map<String, String> sugestaoNaoGostoDe = {
  "ACORDAR CEDO": 'acordarCedo.jpg',
  "PESSOAS MAL EDUCADAS": 'malEducado.jpg',
  "SOM ALTO": 'somAlto.jpg',
  "DORMIR TARDE": 'dormirTarde.jpg',
  "CHUVA": 'chuva.jpg',
  "SOL FORTE": 'solQuente.jpg',
  "FAZER ATIVIDADE FÍSICA": 'atividadeFisica.jpg',
  "COMER VERDURAS": 'comerVerduras.jpg',
  "FOFOCA": 'fofoca.jpg',
  "TRÂNSITO": 'transito.jpg',
  "BUZINA": 'buzina.jpg',
  "COMIDA FRIA": 'comidaFria.jpg',
  "COMIDA QUENTE": 'comidaQuente.jpg',
  "FICAR SOZINHO": 'ficarSozinho.jpg',
  "FICAR SOZINHA": 'ficarSozinha.jpg',
  "ELEVADOR": 'elevador.jpg',
  "ESCADA ROLANTE": 'escadaRolante.jpg',
};

Map<String, String> sugestaoCorPreferida = {
  "AZUL CLARO": 'azulClaro.jpg',
  "AZUL ESCURO": 'azulEscuro.jpg',
  "AMARELO": 'amarelo.jpg',
  "ROSA CLARO": 'rosaClaro.jpg',
  "ROSA PINK": 'rosaPink.jpg',
  "VERDE": 'verde.jpg',
  "PRETO": 'preto.jpg',
  "BRANCO": 'branco.jpg',
  "CINZA": 'cinza.jpg',
  "BEGE": 'bege.jpg',
  "LILÁS": 'lilas.jpg',
  "LARANJA": 'laranja.jpg',
  "VERMELHO": 'vermelho.jpg',
};

Map<String, String> sugestaoSigno = {
  "ÁRIES": 'aries.jpg',
  "LIBRA": 'libra.jpg',
  "VIRGEM": 'virgem.jpg',
  "LEÃO": 'leao.jpg',
  "SAGITÁRIO": 'sagitario.jpg',
  "PEIXES": 'peixes.jpg',
  "ESCORPIÃO": 'escorpiao.jpg',
  "AQUÁRIO": 'aquario.jpg',
  "TOURO": 'touro.jpg',
  "CÂNCER": 'cancer.jpg',
  "GÊMEOS": 'gemeos.jpg',
  "CAPRICÓRNIO": 'capricornio.jpg',
};

List<String> sugestaoEscolaridade = [
  "ENSINO FUNDAMENTAL",
  "ENSINO MÉDIO",
  "FACULDADE",
  "EDUCAÇÃO AO LONGO DA VIDA",
];

Map<String, String> sugestaoAtividades = {
  "ARTESANATO": 'artesanato.jpg',
  "PINTURA": 'pintura.jpg',
  "DANÇA": 'dancar.jpg',
  "ARTES": 'artes.jpg',
  "MÚSICA": 'musica.jpg',
  "ESPORTE": 'esporte.jpg',
  "JARDINAGEM": 'jardinagem.jpg',
  "HORTA": 'horta.jpg',
  "CULINÁRIA": 'culinaria.jpg',
  "JOGOS": 'jogos.jpg',
  "ALFABETIZAÇÃO": 'alfabetizacao.jpg',
};

List<String> sugestaoRelacionamento = [
  "SOLTEIRO",
  "NAMORANDO (RELACIONAMENTO SÉRIO)",
  "CASADO",
  "NOIVO",
  "VIÚVO",
  "SEPARADO",
  "DIVORCIADO",
];

Map<String, String> sugestaoHobbies = {
  "ARTESANATO": 'artesanato.jpg',
  "DANÇAR": 'dancar.jpg',
  "OUVIR MÚSICA": 'ouvirMusica.jpg',
  "FAZER TEATRO": 'fazerTeatro.jpg',
  "FAZER DOBRADURAS (ORIGAMI)": 'fazerOrigami.jpg',
  "TOCAR INSTRUMENTO MUSICAL": 'musica.jpg',
  "JARDINAGEM": 'jardinagem.jpg',
  "CULINÁRIA": 'cozinhar.jpg',
  "JOGOS": 'jogos.jpg',
  "LEITURA": 'leitura.jpg',
  "ASSISTIR FILME": 'assistirFilme.jpg',
  "FOTOGRAFIA": 'fotografia.jpg',
  "ENCONTRAR AMIGOS": 'encontrarAmigos.jpg',
  "FAZER PALAVRA CRUZADA": 'palavraCruzada.jpg',
  "PASSEAR COM CACHORRO": 'passearComCachorro.jpg',
  "VIAJAR": 'viajar.jpg',
  "FAZER QUEBRA CABEÇA": 'quebraCabeca.jpg',
  "PESCARIA": 'pescar.jpg',
  "ACAMPAR": 'acampar.jpg',
  "FAZER TRILHA": 'fazerTrilha.jpg',
  "COLECIONAR COISAS": 'colecionarCoisas.jpg',
};
